      SUBROUTINE RDPPATV (L)
C----------
C RD $Id: rdppatv.f 2454 2018-07-18 23:01:17Z gedixon $
C----------
C
C  RETURNS L=TRUE, TO INDICATE THAT ROOT DISEASE MODEL IS AVAILABLE
C  TO PARALLEL PROCESSOR.
C
C  CALLED BY :
C     GETSTD  [PARALLEL PROCESSOR]
C     PUTSTD  [PARALLEL PROCESSOR]
C
C  CALLS     :
C     NONE
C
C  PARAMETERS :
C     L     - FLAG THAT IS SET TO TRUE WHEN THE ROOT DISEASE MODEL IS
C             ATTACHED WITH PPE.
C
      LOGICAL L

      L = .TRUE.

      RETURN
      END
