      SUBROUTINE MAICAL
      IMPLICIT NONE
C----------
C KT $Id: maical.f 2449 2018-07-11 14:53:35Z gedixon $
C----------
C  THIS SUBROUTINE CALCULATES THE MAI FOR THE STAND. IT IS CALLED
C  FROM CRATET. FOR INLAND EMPIRE THIS ROUTINE IS A DUMMY.
C----------
C
      RETURN
      END
