      SUBROUTINE BWEUKY (KEYWRD)
      IMPLICIT NONE
C----------
C WSBWE $Id: bweuky.f 2460 2018-07-24 14:41:48Z gedixon $
C----------
C  THESE ROUTINES CONVERT KEYWORDS THAT ARE INPUT IN LOWER CASE LETTERS
C  TO UPPER CASE LETTERS.
C----------
      CHARACTER*8 KEYWRD
      INTEGER I

      DO 40 I=1,8
      CALL BWEUCA(KEYWRD(I:I))
   40 CONTINUE
      RETURN
      END
