      SUBROUTINE RGNTHW(LESTB,ITRNIN)
      IMPLICIT NONE
C----------
C CANADA-ON $Id: rgnthw.f 2461 2018-07-24 18:00:57Z gedixon $
C----------
C  ROUTINE NOT USED IN ON VARIANT; PRESERVED FOR COMPATIBILTIY WITH OLD CALLS

      LOGICAL LESTB
	INTEGER ITRNIN

      RETURN
      END
