      SUBROUTINE DAMCDS (II,ICODES)
      IMPLICIT NONE
C----------
C BASE $Id: damcds.f 2355 2018-05-18 17:21:33Z lancedavid $
C----------
C
C     II    = TREE POINTER FOR LIVE TREES
C     ICODES= DISEASE AND DAMAGE CODES ARRAY
C
C----------
C
COMMONS
C
      INCLUDE 'PRGPRM.F77'
      INCLUDE 'ARRAYS.F77'
      INTEGER   I,II
      INTEGER ICODES(6)

C----------
C  CALL SUBROUTINE TO PROCESS DAMAGE CODES FOR BASE MODEL (SPECIAL
C  TREE STATUS CODES, PERCENT DEFECT).
C----------
      CALL BASDAM (II,ICODES)

C----------
C  STORE DAMAGE CODES FOR LATER PEST EXTENSION PROCESSING.
C----------
      DO I = 1,6
        DAMSEV(I,II) = ICODES(I)
      END DO
      	
      RETURN
      END
