      BLOCK DATA SVBLKD
      IMPLICIT NONE
C----------
C  $Id: svblkd.f 2355 2018-05-18 17:21:33Z lancedavid $
C----------
C
C     STAND VISUALIZATION GENERATION
C     N.L.CROOKSTON -- RMRS MOSCOW -- NOVEMBER 1998
C
C     INITIALIZE VISUALIZATION VARIABLES
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'SVDATA.F77'
C
C
COMMONS
C
      DATA NIMAGE/0/
      END
