      SUBROUTINE TMDAM (II, ICODES)
      IMPLICIT NONE
C----------
C DFTM $Id: tmdam.f 2446 2018-07-09 22:54:33Z gedixon $
C----------
C
C     CALLED BY PROGNOSIS VERSION 6.0
C     CALLED BY:  SUBAROUTINE DAMCDS
C
C     THIS ROUTINE WILL BE USED IN FUTURE UPDATES TO THE DOUGLAS FIR TUSSOCK
C     MOTH MODEL.  IT WILL BE USED TO READ IN DAMAGE CODES FROM THE STAND DATA.
C
C     FVS TREE VARIABLES THAT MAY BE NEEDED FOR PROCESSING OF DAMAGE CODES
C     CAN BE ACCESSED BY INCLUDING THE NECESSARY COMMON BLOCKS.
C
      INTEGER II, ICODES(6)

      RETURN
      END

