      SUBROUTINE NATCRZ (IWHO)
      IMPLICIT NONE
C----------
C CANADA-BC $Id: natcrz.f 2461 2018-07-24 18:00:57Z gedixon $
C----------
C
C     CREATE A FILE FOR PROCESSING THROUGH THE NATIONAL CRUISE SYSTEM
C     VOLUME ROUTINE
C
C     IWHO=1 IF CALLED FROM MAIN, IWHO=2 IF CALLED FROM CUTS
C     **THIS VERSION IS A STUB: NATCRZ NOTE USED IN BC**
C
      INTEGER IWHO
      RETURN
	END
