      SUBROUTINE ESMSGS (JOREGT)
      IMPLICIT NONE
C----------
C STRP $Id: esmsgs.f 2456 2018-07-22 14:50:53Z gedixon $
C----------
C
C     CALLED FROM ESIN TO PRINT HABITAT TYPE GROUPS FOR THE
C     REGENERATION ESTABLISHMENT MODEL.
C
C
      INTEGER JOREGT
C
      WRITE(JOREGT,100)
  100 FORMAT('HABITAT TYPE GROUPS USED IN THE REGENERATION',
     &  ' ESTABLISHMENT MODEL',//,'GROUP   HABITAT TYPES',/,
     &  '-----   ',34('-'),/)
      RETURN
      END
