      SUBROUTINE FORMCL(ISPC,IFOR,D,FC)
      IMPLICIT NONE
C----------
C SN $Id: formcl.f 2455 2018-07-19 19:58:41Z gedixon $
C----------
C
      INTEGER IFOR,ISPC
      REAL FC,D
C
C  THIS IS A DUMMY ROUTINE TO RETURN FORMCLASS 80 TO CALLING ROUTINE
C
      FC= 80
C
      RETURN
      END
