      SUBROUTINE SVHABT(XMOD)
      IMPLICIT NONE
C----------
C BASE $Id: svhabt.f 2438 2018-07-05 16:54:21Z gedixon $
C----------
C
C     STAND VISUALIZATION GENERATION
C     J.J.MARCHINEK -- RMRS MOSCOW -- JUNE 1998
C
C     USED FOR PROCESSING HABITAT INFORMATION FOR SNAGS
C
COMMONS
C
C
      INCLUDE 'PRGPRM.F77'
C
C
      INCLUDE 'SVDEAD.F77'
C
C
COMMONS
C
C
      REAL XMOD
      XMOD=1.

      RETURN
      END
