      SUBROUTINE REVISE (VAR,REV)
      IMPLICIT NONE
C----------
C CANADA-ON $Id: revise.f 2472 2018-08-20 21:22:34Z gedixon $
C----------
C  (DON'T CHANGE THIS DATE UNLESS THE SUBROUTINE LOGIC CHANGES.)
C----------
C
C  THIS ROUTINE PROVIDES THE LATEST REVISION DATE FOR EACH VARIANT
C  WHICH GETS PRINTED IN THE MAIN HEADER ON THE OUTPUT.
C  CALLED FROM GROHED, FILOPN, SUMHED, SUMOUT, ECVOLS, PRTRLS,
C  AND DGDRIV.
C----------
      CHARACTER VAR*2,REV*10
C----------
C ONTARIO - BASED ON LAKE STATES
C----------
      SELECT CASE (VAR)
        CASE('ON')
          REV = '10/01/12'
        CASE DEFAULT
          REV = 'UNKNOWN '
      END SELECT
C
      RETURN
      END
