C----------
C VOLUME $Id: volinput_mod.f 2458 2018-07-22 19:09:30Z gedixon $
C----------
      MODULE VOLINPUT_MOD
      IMPLICIT  NONE

        INTEGER      FORMCLASS
        CHARACTER*1  MRULEMOD
        INTEGER NEWEVOD,NEWOPT
        REAL NEWMAXLEN,NEWMINLEN,NEWMINLENT,NEWMERCHL,NEWMTOPP
        REAL NEWMTOPS,NEWSTUMP,NEWTRIM,NEWBTR,NEWDBTBH,NEWMINBFD
        CHARACTER*1 NEWCOR
      END MODULE VOLINPUT_MOD